name: Test Starter Kit Installation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  php-tests:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    name: Test Starter Kit Installation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./starter-kit

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create a new Statamic Project
        run: composer create-project statamic/statamic app --no-interaction

      - name: Link Starter Kit to Statamic Project
        working-directory: ./app
        run: |
          composer config minimum-stability dev
          composer config repositories.starter-kit path ../starter-kit

      - name: Install Starter Kit
        working-directory: ./app
        run: php please starter-kit:install statamic/starter-kit-cool-writings --local --no-interaction

      - name: List Installed Dependencies
        working-directory: ./app
        run: composer show -D

      - name: Tests can be executed on Statamic Project
        working-directory: ./app
        run: vendor/bin/phpunit

      - name: Test Assets can be build
        working-directory: ./app
        run: |
          npm update
          npm run build
